
create database XingTest;
use XingTest;

CREATE TABLE Block (TimeStamp VARCHAR(20) NOT NULL ,BlockNumber VARCHAR(10) NOT NULL,BlockHash CHAR(66) NOT NULL ,BlockParentHash CHAR(66) NOT NULL,Nonce VARCHAR(50)  NOT NULL,UncleHash CHAR(66) NOT NULL ,LogsBloom VARCHAR(1000) NOT NULL ,TxsRoot CHAR(66) NOT NULL,StateRoot  CHAR(66) NOT NULL,ReceiptRoot CHAR(66) NOT NULL,Miner CHAR(42) NOT NULL,
        Difficulty VARCHAR(20) NOT NULL ,Td VARCHAR(40) NOT NULL,Size VARCHAR(10) NOT NULL,ExtraData VARCHAR(1000) NOT NULL ,GasLimit VARCHAR(20) NOT NULL,GasUsed VARCHAR(20) NOT NULL,TxNums VARCHAR(20) NOT NULL, PRIMARY KEY(BlockNUmber));
        
CREATE TABLE OutTx(TxHash VARCHAR(66) NOT NULL,BlockNumber VARCHAR(10) NOT NULL,BlockHash CHAR(66) NOT NULL,TimeStamp VARCHAR(20) NOT NULL,TxIndex VARCHAR(20) NOT NULL,Tag VARCHAR(15) NOT NULL,FromAddress CHAR(42) NOT NULL,ToAddress CHAR(42) NOT NULL,Value VARCHAR(100) NOT NULL,GasLimit VARCHAR(20) NOT NULL,GasUsed VARCHAR(20) NOT NULL,GasPrice VARCHAR(20) NOT NULL,InputData MEDIUMTEXT NOT NULL,Nonce VARCHAR(20) NOT NULL,ToType VARCHAR(8) NOT NULL,FromType VARCHAR(8) NOT NULL,TxStatus CHAR(1) NOT NULL, PRIMARY KEY (TxHash)) ;
 
CREATE TABLE Log(BlockLogIndex VARCHAR(20) NOT NULL  ,BlockTimeStamp VARCHAR(20) NOT NULL ,BlockNumber VARCHAR(10) NOT NULL ,BlockHash CHAR(66) NOT NULL ,TxHash CHAR(66) NOT NULL , TxIndex VARCHAR(20) NOT NULL ,OriginatedAddress CHAR(42) NOT NULL , Data MEDIUMTEXT NOT NULL , Topics VARCHAR(1000) NOT NULL, PRIMARY KEY (TxHash,BlockLogIndex));


CREATE TABLE InTx(TxCallSeq VARCHAR(10) NOT NULL,TxLayer VARCHAR(10) NOT NULL,TxHash CHAR(66) NOT NULL,FromAddr CHAR(42) NOT NULL,ToAddr CHAR(42) NOT NULL,InputData MEDIUMTEXT NOT NULL,Value VARCHAR(100) NOT NULL,Tag VARCHAR(15) NOT NULL,FromType VARCHAR(8) NOT NULL,ToType VARCHAR(8) NOT NULL,IntrinsicGas VARCHAR(20) NOT NULL,GasUsed VARCHAR(20) NOT NULL,Error VARCHAR(20) NOT NULL,PRIMARY KEY (TxHash,TxCallSeq));

CREATE TABLE TokenTrans(TokenAddr CHAR(42) NOT NULL,FromAddr CHAR(77) NOT NULL,ToAddr CHAR(77) NOT NULL,Value VARCHAR(100) NOT NULL,
    TxHash CHAR(66) NOT NULL,LogIndex VARCHAR(20) NOT NULL,BlockTimeStamp VARCHAR(20) NOT NULL,BlockNumber VARCHAR(10) NOT NULL,BlockHash CHAR(66) NOT NULL,PRIMARY KEY (TokenAddr,TxHash,LogIndex) );

CREATE TABLE Contract(Address CHAR(46) NOT NULL ,Balance VARCHAR(40) NOT NULL, Bytecode MEDIUMTEXT NOT NULL,MethodId VARCHAR(1000) NOT NULL,
    BlockTimeStamp VARCHAR(20) NOT NULL,BlockNumber VARCHAR(10) NOT NULL,BlockHash CHAR(66) NOT NULL,IsERC20 VARCHAR(5) NOT NULL,Nonce VARCHAR(20) NOT NULL,PRIMARY KEY (Address)) ;

CREATE TABLE Trace(TxHash CHAR(66) NOT NULL,TxTrace MEDIUMTEXT NOT NULL,ToAddress CHAR(42) NOT NULL,OutOfGasTrace MEDIUMTEXT NOT NULL,PRIMARY KEY (TxHash)) ;

CREATE TABLE Eoa(Address CHAR(46) NOT NULL, Balance VARCHAR(40) NOT NULL, Nonce VARCHAR(20) NOT NULL, PRIMARY KEY (Address));
